package main

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func schemaDir(t *testing.T) string {
	t.Helper()
	// Find schema dir relative to this test file.
	dir := filepath.Join("..", "..", "schema", "tmp")
	if _, err := os.Stat(dir); err != nil {
		t.Skipf("schema dir not found: %v", err)
	}
	abs, _ := filepath.Abs(dir)
	return abs
}

func TestLoadSchemas(t *testing.T) {
	ir, err := LoadSchemas(schemaDir(t))
	require.NoError(t, err, "LoadSchemas")

	assert.Len(t, ir.Enums, 5, "enums count")

	// Check all expected struct names exist.
	want := map[string]bool{
		"ContextMatchRequest":  true,
		"ContextMatchResponse": true,
		"IdentityMatchRequest": true,
		"IdentityMatchResponse": true,
		"ExposeRequest":        true,
		"ExposeResponse":       true,
		"ErrorResponse":        true,
		"Geo":                  true,
		"Metro":                true,
		"Offer":                true,
		"OfferPrice":           true,
		"AvailablePackage":     true,
		"Catalog":              true,
		"BrandRef":             true,
		"Signals":              true,
		"KeyValuePair":         true,
		"PackageEligibility":   true,
	}
	got := make(map[string]bool)
	for _, s := range ir.Structs {
		got[s.Name] = true
	}
	for name := range want {
		assert.True(t, got[name], "missing struct: %s", name)
	}
	assert.Equal(t, len(want), len(ir.Structs), "struct count")
}

func TestRender(t *testing.T) {
	ir, err := LoadSchemas(schemaDir(t))
	require.NoError(t, err, "LoadSchemas")

	src, err := Render("tmproto", ir)
	require.NoError(t, err, "Render")

	code := string(src)

	// Must contain the generated header.
	assert.Contains(t, code, "Code generated by internal/generate; DO NOT EDIT.")

	// Must contain package declaration.
	assert.Contains(t, code, "package tmproto")

	// Spot-check key types.
	checks := []struct {
		name    string
		substr  string
	}{
		{"ContextMatchRequest struct", "type ContextMatchRequest struct"},
		{"PropertyType string", "type PropertyType string"},
		{"PropertyTypeWebsite", "PropertyTypeWebsite"},
		{"json available_packages", `json:"available_packages"`},
		{"AvailablePkgs", "AvailablePkgs"},
		{"*Geo pointer", "*Geo"},
		{"*float64 pointer", "*float64"},
		{"map[string]string", "map[string]string"},
	}
	for _, tc := range checks {
		t.Run(tc.name, func(t *testing.T) {
			assert.Contains(t, code, tc.substr, "missing in output: %q", tc.substr)
		})
	}
}

func TestGoldenFile(t *testing.T) {
	ir, err := LoadSchemas(schemaDir(t))
	require.NoError(t, err, "LoadSchemas")

	generated, err := Render("tmproto", ir)
	require.NoError(t, err, "Render")

	goldenPath := filepath.Join("..", "..", "tmproto", "types_gen.go")
	golden, err := os.ReadFile(goldenPath)
	require.NoError(t, err, "read golden file")

	assert.Equal(t, string(golden), string(generated), "generated output differs from golden file (tmproto/types_gen.go); run go generate ./tmproto/...")
}

func TestEnumCompleteness(t *testing.T) {
	ir, err := LoadSchemas(schemaDir(t))
	require.NoError(t, err, "LoadSchemas")

	// Each enum should have at least 2 values.
	for _, e := range ir.Enums {
		t.Run(e.Name, func(t *testing.T) {
			assert.GreaterOrEqual(t, len(e.Values), 2, "enum %s has too few values", e.Name)
		})
	}
}
