package main

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func testDirs(t *testing.T) (schemaDir, enumDir, overlayPath string) {
	t.Helper()
	schemaDir = filepath.Join("..", "..", "adcp", "schemas", "tmp")
	if _, err := os.Stat(schemaDir); err != nil {
		t.Skipf("schema dir not found: %v", err)
	}
	schemaDir, _ = filepath.Abs(schemaDir)

	enumDir = filepath.Join("..", "..", "adcp", "schemas", "enums")
	if _, err := os.Stat(enumDir); err != nil {
		t.Skipf("enum dir not found: %v", err)
	}
	enumDir, _ = filepath.Abs(enumDir)

	overlayPath = "go-overlays.json"
	if _, err := os.Stat(overlayPath); err != nil {
		t.Skipf("overlay file not found: %v", err)
	}

	return schemaDir, enumDir, overlayPath
}

func TestLoadSchemas(t *testing.T) {
	schemaDir, enumDir, overlayPath := testDirs(t)
	ir, err := LoadSchemas(schemaDir, enumDir, overlayPath)
	require.NoError(t, err, "LoadSchemas")

	// Expected enums from overlay.
	assert.Len(t, ir.Enums, 7, "enums count")

	// Check all expected struct names exist (post-overlay rename).
	want := map[string]bool{
		"ContextMatchRequest":   true,
		"ContextMatchResponse":  true,
		"IdentityMatchRequest":  true,
		"IdentityMatchResponse": true,
		"ErrorResponse":         true,
		"ProviderRegistration":  true,
		"Offer":                 true,
		"OfferPrice":            true,
		"AvailablePackage":      true,
	}
	got := make(map[string]bool)
	for _, s := range ir.Structs {
		got[s.Name] = true
	}
	for name := range want {
		assert.True(t, got[name], "missing struct: %s", name)
	}
	assert.Equal(t, len(want), len(ir.Structs), "struct count")
}

func TestRender(t *testing.T) {
	schemaDir, enumDir, overlayPath := testDirs(t)
	ir, err := LoadSchemas(schemaDir, enumDir, overlayPath)
	require.NoError(t, err, "LoadSchemas")

	src, err := Render("tmproto", ir)
	require.NoError(t, err, "Render")

	code := string(src)

	// Must contain the generated header.
	assert.Contains(t, code, "Code generated by internal/generate; DO NOT EDIT.")

	// Must contain package declaration.
	assert.Contains(t, code, "package tmproto")

	// Spot-check key types.
	checks := []struct {
		name   string
		substr string
	}{
		{"ContextMatchRequest struct", "type ContextMatchRequest struct"},
		{"PropertyType string", "type PropertyType string"},
		{"PropertyTypeWebsite", "PropertyTypeWebsite"},
		{"UIDType string", "type UIDType string"},
		{"UIDTypeRampID", "UIDTypeRampID"},
		{"OfferPrice struct", "type OfferPrice struct"},
		{"Offer struct", "type Offer struct"},
		{"request_id json", `json:"request_id"`},
		{"property_type json", `json:"property_type"`},
	}
	for _, tc := range checks {
		t.Run(tc.name, func(t *testing.T) {
			assert.Contains(t, code, tc.substr, "missing in output: %q", tc.substr)
		})
	}
}

func TestGoldenFile(t *testing.T) {
	schemaDir, enumDir, overlayPath := testDirs(t)
	ir, err := LoadSchemas(schemaDir, enumDir, overlayPath)
	require.NoError(t, err, "LoadSchemas")

	generated, err := Render("tmproto", ir)
	require.NoError(t, err, "Render")

	goldenPath := filepath.Join("..", "..", "tmproto", "types_gen.go")
	golden, err := os.ReadFile(goldenPath)
	require.NoError(t, err, "read golden file")

	assert.Equal(t, string(golden), string(generated), "generated output differs from golden file (tmproto/types_gen.go); run go generate ./tmproto/...")
}

func TestEnumCompleteness(t *testing.T) {
	schemaDir, enumDir, overlayPath := testDirs(t)
	ir, err := LoadSchemas(schemaDir, enumDir, overlayPath)
	require.NoError(t, err, "LoadSchemas")

	// Each enum should have at least 2 values.
	for _, e := range ir.Enums {
		t.Run(e.Name, func(t *testing.T) {
			assert.GreaterOrEqual(t, len(e.Values), 2, "enum %s has too few values", e.Name)
		})
	}
}

func TestOverlayFieldOverrides(t *testing.T) {
	schemaDir, enumDir, overlayPath := testDirs(t)
	ir, err := LoadSchemas(schemaDir, enumDir, overlayPath)
	require.NoError(t, err, "LoadSchemas")

	src, err := Render("tmproto", ir)
	require.NoError(t, err, "Render")

	code := string(src)

	// Overlay sets ContextMatchRequest.artifact to *json.RawMessage.
	assert.True(t, strings.Contains(code, "*json.RawMessage"), "expected *json.RawMessage from overlay field override")

	// Overlay sets refs for /schemas/core/property-id.json to string.
	// So ContextMatchRequest.property_id should be string.
	assert.True(t, strings.Contains(code, "PropertyID") && strings.Contains(code, `json:"property_id`), "expected PropertyID field from overlay ref override")
}

func TestRefToGoType(t *testing.T) {
	ctx := &loadContext{
		overlay: &Overlay{
			Refs: map[string]string{
				"/schemas/core/property-id.json": "string",
			},
		},
		enumReg:   enumRegistry{"/schemas/enums/property-type.json": "PropertyType"},
		structReg: structRegistry{"/schemas/tmp/offer.json": "Offer"},
	}

	tests := []struct {
		ref  string
		want string
	}{
		{"/schemas/enums/property-type.json", "PropertyType"},
		{"/schemas/tmp/offer.json", "Offer"},
		{"/schemas/core/property-id.json", "string"},
		{"enums.json#/$defs/PropertyType", "PropertyType"},
	}

	for _, tt := range tests {
		got := refToGoType(tt.ref, ctx)
		assert.Equal(t, tt.want, got, "refToGoType(%q)", tt.ref)
	}
}

func TestTitleToPascalCase(t *testing.T) {
	tests := []struct {
		title string
		want  string
	}{
		{"Context Match Request", "ContextMatchRequest"},
		{"TMP Error", "TmpError"},
		{"Property Type", "PropertyType"},
		{"UID Type", "UIDType"},
		{"Offer Price", "OfferPrice"},
		{"Metric Type (Deprecated)", "MetricTypeDeprecated"},
	}
	for _, tt := range tests {
		got := titleToPascalCase(tt.title)
		assert.Equal(t, tt.want, got, "titleToPascalCase(%q)", tt.title)
	}
}

func TestLoadWithoutOverlay(t *testing.T) {
	schemaDir := filepath.Join("..", "..", "adcp", "schemas", "tmp")
	if _, err := os.Stat(schemaDir); err != nil {
		t.Skipf("schema dir not found: %v", err)
	}
	schemaDir, _ = filepath.Abs(schemaDir)

	enumDir := filepath.Join("..", "..", "adcp", "schemas", "enums")
	if _, err := os.Stat(enumDir); err != nil {
		t.Skipf("enum dir not found: %v", err)
	}
	enumDir, _ = filepath.Abs(enumDir)

	// Without overlay: all enums should be loaded.
	ir, err := LoadSchemas(schemaDir, enumDir, "")
	require.NoError(t, err, "LoadSchemas without overlay")

	assert.NotEmpty(t, ir.Enums, "expected enums when loading without overlay")
	assert.NotEmpty(t, ir.Structs, "expected structs when loading without overlay")
}
