package main

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func schemaDir(t *testing.T) string {
	t.Helper()
	// Find schema dir relative to this test file.
	dir := filepath.Join("..", "..", "schema", "tmp")
	if _, err := os.Stat(dir); err != nil {
		t.Skipf("schema dir not found: %v", err)
	}
	abs, _ := filepath.Abs(dir)
	return abs
}

func TestLoadSchemas(t *testing.T) {
	ir, err := LoadSchemas(schemaDir(t))
	if err != nil {
		t.Fatalf("LoadSchemas: %v", err)
	}

	if len(ir.Enums) != 5 {
		t.Errorf("enums: got %d, want 5", len(ir.Enums))
	}

	// Check all expected struct names exist.
	want := map[string]bool{
		"ContextMatchRequest":  true,
		"ContextMatchResponse": true,
		"IdentityMatchRequest": true,
		"IdentityMatchResponse": true,
		"ExposeRequest":        true,
		"ExposeResponse":       true,
		"ErrorResponse":        true,
		"Geo":                  true,
		"Metro":                true,
		"Offer":                true,
		"OfferPrice":           true,
		"AvailablePackage":     true,
		"Catalog":              true,
		"BrandRef":             true,
		"Signals":              true,
		"KeyValuePair":         true,
		"PackageEligibility":   true,
	}
	got := make(map[string]bool)
	for _, s := range ir.Structs {
		got[s.Name] = true
	}
	for name := range want {
		if !got[name] {
			t.Errorf("missing struct: %s", name)
		}
	}
	if len(ir.Structs) != len(want) {
		t.Errorf("struct count: got %d, want %d", len(ir.Structs), len(want))
	}
}

func TestRender(t *testing.T) {
	ir, err := LoadSchemas(schemaDir(t))
	if err != nil {
		t.Fatalf("LoadSchemas: %v", err)
	}

	src, err := Render("tmp", ir)
	if err != nil {
		t.Fatalf("Render: %v", err)
	}

	code := string(src)

	// Must contain the generated header.
	if !strings.Contains(code, "Code generated by internal/generate; DO NOT EDIT.") {
		t.Error("missing generated header")
	}

	// Must contain package declaration.
	if !strings.Contains(code, "package tmp") {
		t.Error("missing package declaration")
	}

	// Spot-check key types.
	checks := []string{
		"type ContextMatchRequest struct",
		"type PropertyType string",
		"PropertyTypeWebsite",
		`json:"available_packages"`,
		"AvailablePkgs",
		"*Geo",
		"*float64",
		"map[string]string",
	}
	for _, check := range checks {
		if !strings.Contains(code, check) {
			t.Errorf("missing in output: %q", check)
		}
	}
}

func TestGoldenFile(t *testing.T) {
	ir, err := LoadSchemas(schemaDir(t))
	if err != nil {
		t.Fatalf("LoadSchemas: %v", err)
	}

	generated, err := Render("tmp", ir)
	if err != nil {
		t.Fatalf("Render: %v", err)
	}

	goldenPath := filepath.Join("..", "..", "tmp", "types_gen.go")
	golden, err := os.ReadFile(goldenPath)
	if err != nil {
		t.Fatalf("read golden file: %v", err)
	}

	if string(generated) != string(golden) {
		t.Error("generated output differs from golden file (tmp/types_gen.go); run go generate ./tmp/...")
	}
}

func TestEnumCompleteness(t *testing.T) {
	ir, err := LoadSchemas(schemaDir(t))
	if err != nil {
		t.Fatalf("LoadSchemas: %v", err)
	}

	// Each enum should have at least 2 values.
	for _, e := range ir.Enums {
		if len(e.Values) < 2 {
			t.Errorf("enum %s has only %d values", e.Name, len(e.Values))
		}
	}
}
