package main

import (
	"bytes"
	"fmt"
	"go/format"
	"sort"
	"text/template"
)

// Render produces formatted Go source for the given IR.
func Render(pkg string, ir *IR) ([]byte, error) {
	if err := validateIdentifier("package name", pkg); err != nil {
		return nil, err
	}
	type tplField struct {
		Name    string
		Type    string
		JSONTag string
		Comment string
	}
	type tplStruct struct {
		Name        string
		Description string
		Fields      []tplField
	}

	structs := make([]tplStruct, len(ir.Structs))
	for i, s := range ir.Structs {
		ts := tplStruct{Name: s.Name, Description: s.Description}
		for _, f := range s.Fields {
			tag := f.JSONName
			if f.OmitEmpty {
				tag += ",omitempty"
			}
			ts.Fields = append(ts.Fields, tplField{
				Name:    f.Name,
				Type:    f.Type,
				JSONTag: tag,
				Comment: f.Comment,
			})
		}
		structs[i] = ts
	}

	funcMap := template.FuncMap{
		"goString": func(s string) string { return fmt.Sprintf("%q", s) },
	}
	t := template.Must(template.New("gen").Funcs(funcMap).Parse(genTemplate))

	// Detect needed imports by scanning field types.
	imports := collectImports(ir)

	data := struct {
		Package string
		Imports []string
		Enums   []GoEnum
		Structs []tplStruct
	}{
		Package: pkg,
		Imports: imports,
		Enums:   ir.Enums,
		Structs: structs,
	}

	var buf bytes.Buffer
	if err := t.Execute(&buf, data); err != nil {
		return nil, err
	}

	return format.Source(buf.Bytes())
}

// collectImports scans the IR for field types that require stdlib imports.
func collectImports(ir *IR) []string {
	needed := map[string]string{
		"json.RawMessage": "encoding/json",
	}
	imports := map[string]bool{}
	for _, s := range ir.Structs {
		for _, f := range s.Fields {
			for prefix, pkg := range needed {
				if f.Type == prefix || f.Type == "*"+prefix || f.Type == "[]"+prefix {
					imports[pkg] = true
				}
			}
		}
	}
	var result []string
	for pkg := range imports {
		result = append(result, pkg)
	}
	sort.Strings(result)
	return result
}

const genTemplate = `// Code generated by internal/generate; DO NOT EDIT.

// Package {{ .Package }} defines the Trusted Match Protocol message types.
//
// TMP separates ad decisioning into two independent operations:
// Context Match (what content is this?) and Identity Match (is this user eligible?).
// The two operations never share data. The publisher joins them locally.
package {{ .Package }}
{{ if .Imports }}
import (
{{- range .Imports }}
	"{{ . }}"
{{- end }}
)
{{ end }}
{{ range .Enums }}
// {{ .Description }}
type {{ .Name }} string

const (
{{- $enumName := .Name }}
{{- range .Values }}
	{{ .ConstName }} {{ $enumName }} = {{ goString .Value }}
{{- end }}
)
{{ end }}
{{- range .Structs }}
// {{ .Description }}
type {{ .Name }} struct {
{{- range .Fields }}
	{{ .Name }} {{ .Type }} ` + "`" + `json:"{{ .JSONTag }}"` + "`" + `{{ if .Comment }} // {{ .Comment }}{{ end }}
{{- end }}
}
{{ end }}
`
